### ISSUE TITLE
Music crashes builded gane

### ISSUE THREAD

**Issue by LeadheadOnline** [bladecoder/bladecoder-adventure-engine#49]
All of my music tracks have worked perfectly in both the debug testing, and the packaged game, but my newest track crashes a packaged game, while working fine in tests. It's roughly 2 minutes long, and I've tried everything from 320 to 128 Kb/s. Any ideas?

**Comment by bladecoder** [comment]
If you execute your package game from the command line, a log error will shows. Can you send me the error log, please?

I think that your problem is with the name of the track. If you work in Windows, probably you reference in the editor the name with an incorrect case. The packaged game is case-sensitive for filenames, while in test mode can works (only on Windows). Can you check it?

**Comment by LeadheadOnline** [comment]
After making the filename in the editor match the case of the actual filename, it worked perfectly! Thanks a ton, this engine really is fantastic for a guy like me

**Comment by bladecoder** [comment]
You can put music to your credits adding the next line at the beginning of the the credits.txt file:

`m#music_filename`

example:

`m#01-bach.mp3`
